services:
  # Master
  spark-driver:
    build:
      context: ./spark/
      dockerfile: Dockerfile
    container_name: spark_driver
    tty: true
    restart: on-failure
    ports:
      - "8080:8080"
    entrypoint: ../driver-entrypoint.sh


  client:
    build:
      context: ./client/
      dockerfile: Dockerfile
    container_name: client
    tty: true
    restart: on-failure
    volumes:
      - './client:/app'