services:
 spark-master:
  build:
    context: ./app/
    dockerfile_inline: |
      FROM bitnami/spark:3.5.0
      COPY . /opt/bitnami/spark/app/
  command: bin/spark-class org.apache.spark.deploy.master.Master
  ports:
    - '8080:8080'
    - '7077:7077'
  environment:
    - SPARK_MASTER_HOST=spark-master


 spark-worker:
  image: bitnami/spark:3.5.0
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
  environment:
    - SPARK_WORKER_CORES=2
    - SPARK_WORKER_MEMORY=2g
    - SPARK_MASTER_URL=spark://spark-master:7077
  depends_on:
   - spark-master